app/components/course-admin/submissions-page/submission-details/header-container.hbs
Removed the font-mono class from the Commit SHA title in order to improve visual
consistency within the Submissions Page. This change makes the text color
consistent with the surrounding elements.
=> refactor: Remove unnecessary font-mono class from Commit SHA title

app/components/course-page/configure-extensions-modal/extension-card.ts, app/models/course-extension-activation.ts, app/models/repository.ts, app/utils/repository-poller.js, mirage/utils/sync-repository-stage-lists.js
- Updated naming conventions from 'course-extension-activations' to 'extension-activations' to provide clarity and consistency throughout the codebase.
- Renamed variables and references in RepositoryPoller, RepositoryModel, CourseExtensionActivation, and ExtensionCardComponent for better code readability and maintainability.
=> refactor: Update naming conventions for extension activations

app/components/affiliate-link-page/accept-referral-container.hbs, app/components/affiliate-link-page/accept-referral-container.ts
Added a check for currentUserCanAccessMembershipBenefits in the `acceptOfferButtonIsEnabled` method to ensure that CodeCrafters members already have full access.
=> feat: Add check for currentUserCanAccessMembershipBenefits in acceptReferralContainer

app/components/tracks-page/track-card.ts, tests/acceptance/view-tracks-test.js
=> CC-1285 Allow challenge deprecation language card in tracks

app/components/course-page/course-stage-step/test-runner-card/run-tests-instructions.hbs, app/components/course-page/course-stage-step/test-runner-card/run-tests-instructions.ts, tests/acceptance/course-page/test-runner-card-test.js
- Rename second stage instructions card to second stage tutorial card across files.
- Rename second-stage instructions card to second-stage tutorial card components.
- Fix ID in second-stage tutorial card and remove unnecessary pause in tests.
- Refactor run-tests-instructions to always recommend CLI and Git options.
=> Recommend Git instead of CLI for stage 2

config/environment.js
Updates the version number in the environment configuration 
to 27.0 to ensure all clients are prompted to update. This 
change prepares the project for future enhancements and 
maintains versioning consistency.
=> chore: update version number to 27.0 for clients

app/controllers/pay.ts, config/environment.js
Update the version number in the environment configuration to 
28.0 to ensure clients are prompted to update. Refine the logic 
for promotional discounts in the PayController to apply the 
discount only for yearly plans, improving clarity and 
functionality.
=> chore: update version number and refine discount logic

package-lock.json
Updates several dependencies in package-lock.json to their latest 
versions, including content-tag, path-to-regexp, lru-cache, tslib, 
and semver. These changes improve compatibility, security, and 
performance by ensuring the project uses the most recent stable 
releases. Additionally, removes outdated entries for @pkgr/utils
=> chore(deps): update package-lock.json for dependencies

README.md
Update the README.md file to change "front-end" to "frontend" for 
consistency and accuracy. This improves clarity and aligns with 
common terminology in web development.
=> fix: correct spelling of "frontend" in README.md

scripts/build-vercel-output.sh
Redirect both stdout and stderr to the log file using a single 
pipeline. This change simplifies the command and ensures that 
all output, including errors, is captured in the build output 
log for better debugging and monitoring.
=> fix: improve logging in build-vercel-output script

app/components/helpscout-beacon.js
Updates the logging level for HelpScout Beacon initialization failure 
from a warning to a log statement. This change aims to reduce 
the severity of the message in the console, making it less 
intrusive while still providing necessary information for 
debugging purposes.
=> fix(logging): change warning to log for HelpScout Beacon

app/helpers/markdown-to-html.ts
Remove unnecessary warning log for DOMPurify in FastBoot mode. 
Return generated HTML directly when in FastBoot, as sanitization 
is not possible. This simplifies the code and avoids confusion 
regarding the sanitization process in this environment.
=> refactor: improve FastBoot handling in MarkdownToHtml helper

app/routes/catalog.ts, app/routes/track.ts, tests/acceptance/course-page/attempt-course-stage-test.js, tests/acceptance/course-page/resume-course-test.js, tests/acceptance/course-page/start-course-test.js, tests/acceptance/course-page/switch-repository-test.js, tests/acceptance/course-page/try-other-language-test.js
Add support for fetching and managing language models in the 
Catalog and Track routes. Introduce a new promise for languages 
in the Catalog route and update the Track route to retrieve 
languages based on the track slug. This enhances the data 
availability for language-related features and improves 
authentication handling for repository data.
=> feat(routes): add language model handling in catalog and track

app/components/track-page/start-track-button.hbs, app/components/track-page/start-track-button.ts
Renames the `handleClicked` method to `handleClick` for improved 
clarity and consistency. Updates the corresponding template to 
reflect this change. Additionally, modifies the transition logic 
to use `conceptSlugs` instead of `concepts` for better alignment 
with the data structure.
=> refactor: rename click handler for clarity

app/components/course-page/course-stage-step/your-task-card/index.ts
=> Add support for {{language_name}} in instructions markdown

app/components/course-admin/code-example-insights/metadata-container.ts, app/models/community-course-stage-solution.ts
Add `highlightedLinesCount`, `addedLinesCount`, and `removedLinesCount` 
attributes to track solution changes effectively. Update the `changedLinesCount` 
getter to return the sum of added and removed lines using the new attributes. 
Include highlighted lines count in the insights display for better visibility 
of code modifications.
=> Add changed line counts to metadata

app/components/course-page/course-stage-step/community-solution-card/index.ts, app/components/course-page/course-stage-step/community-solution-card/more-dropdown.hbs, tests/acceptance/course-page/code-examples/publish-to-github-test.js, tests/acceptance/course-page/code-examples/view-test.js, tests/pages/course/code-examples-page.ts
Refactor the logic for displaying highlighted files in the community 
solution card. Remove the dependency on the current user being staff 
for the presence of highlighted files to ensure compatibility with 
solutions that may not have been migrated yet. Update the template 
to directly check the length of highlightedFiles, improving code 
clarity and maintaining proper functionality across variations of 
solutions.
=> fix: update community solution card logic for highlighted files

app/components/faq-item.hbs, app/components/faq-list.ts
Update FAQ answers to use Markdown instead of HTML. This change 
improves readability, enables easier formatting, and enhances 
consistency across FAQ entries. All instances of the answer field 
are replaced with answerMarkdown, allowing for better 
presentation of content.
=> refactor(faq-list): replace HTML answers with Markdown

vercel-functions/prerender/_prerender-ember-route.func/index.js
Instead of sending a 404 status code if FastBoot didn't return a 200 in Vercel Prerender Functions — send contents of `_empty.html`
=> Send `_empty.html` instead of 404 in prerender functions if FastBoot status code was not 200

app/utils/highlighter-cache.ts
This fixes a deprecation warning coming from `shiki.getHighlighter`, which [has been replaced](https://shiki.style/blog/v2#gethighlighter-createhighlighter) with `shiki.createHighlighter`
> There is no functional changes, but more like correcting the naming to avoid confusion. It should be a straightforward find-and-replace.
=> Fix a shiki deprecation warning for `getHighlighter`

tests/acceptance/settings-page/billing-test.js
This fixes a very annoying warning flood in the tests console, caused by an unnecessary extra `setupMirage` call.
=> Fix warning flood in tests console about a second pretender instance

app/services/store.js, app/services/store.ts
This fixes a VERY annoying deprecation warning about relying on ember-data auto-magically installing the `store` service.
File `app/services/store.js` must NOT be converted to TypeScript, otherwise it will stop overriding the service file ember-data, and will start causing a deprecation warning.
=> Fix a very annoying store auto-injection deprecation warning

.vscode/tasks.json, package.json, vercel.json
Follow-up to https://github.com/codecrafters-io/frontend/pull/2949
This improves our `start` and `start:fastboot` NPM tasks, and adds several other minor improvements
- Task `start` now calls `start:fastboot` instead of `ember serve` directly
- `FASTBOOT_DISABLED=true` now needs to be set only in `start`
- Added `install:silent` task for running `npm install --no-fund --no-audit`
- Added `restart:watchman` task for restarting watchman
- Task `start:fastboot` now runs `install:silent` and `restart:watchman` before running `ember serve`
- it doesn't take any significant time if `node_modules` is up to date, and running these two manually every time is an unnecessary PITA
- Added a **VSCode** task with problem matcher for `lint:js` NPM task
- This allows VSCode to collect errors into …
=> Improve `start` and `start:fastboot` NPM tasks

app/components/leaderboard-page/entries-table/row.hbs, app/components/leaderboard-page/header.hbs, app/components/leaderboard-page/header.ts, tests/acceptance/leaderboard-page/view-test.js, tests/pages/leaderboard-page.ts
Refactor leaderboard page test helper by extracting language dropdown
into its own component and enhancing entries collection to include
username text. Add a new acceptance test to verify that users can
switch between Rust and Python leaderboards, ensuring the URL updates
correctly and leaderboard entries reflect the selected language.
This improves test coverage for multi-language support and ensures UI
correctness when changing the leaderboard language.
=> test(acceptance): add language switch test on leaderboard page

app/routes/leaderboard.ts, tests/acceptance/leaderboard-page/view-test.js
Replace allowsAnonymousAccess property with buildRouteInfoMetadata 
method returning RouteInfoMetadata to declare anonymous access. 
Refactor activate method to properly close function block. This update 
aligns with new route metadata conventions and improves route 
configuration clarity.
=> feat(leaderboard): add route info metadata for anonymous access

app/components/header/account-dropdown.hbs, app/components/header/account-dropdown.ts, app/components/header/index.ts
Add an "Admin Panel" link to the account dropdown menu visible only to
admin users. The link opens the backend admin page in a new tab, using
the backend URL from the environment config. This improves access and
usability for admin users to quickly reach the admin interface.
Also clean up unused admin-related code from the header index component,
removing the admin link generation and adminPanelLink getter that were
previously unused. This simplifies the codebase and consolidates admin
link logic into the account dropdown component.
=> Move admin panel link to account dropdown

app/components/roadmap-info-alert.hbs, app/templates/roadmap/course-extension-ideas.hbs, app/templates/roadmap/course-ideas.hbs
Remove the "hidden md:block" classes from RoadmapInfoAlert components  
to ensure the informational alerts about challenges and extensions are  
visible on all screen sizes. Also, update RoadmapInfoAlert to forward  
HTML attributes to the underlying Alert component for better flexibility.  
These changes improve user awareness of roadmap concepts regardless of  
device or viewport.
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #3102 
- <kbd>&nbsp;1&nbsp;</kbd> #3101 👈
=> feat(roadmap): always show RoadmapInfoAlert on all screen sizes

.github/workflows/publish_bundle.yml, .github/workflows/test.yml
Update all workflow jobs to run on depot-ubuntu-24.04-16 from 
depot-ubuntu-22.04-16. This change ensures the CI environment uses 
the latest Ubuntu LTS version, providing improved security, updated 
packages, and better performance for build, test, and lint workflows.
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #3105 
- <kbd>&nbsp;1&nbsp;</kbd> #3104 👈
=> ci: upgrade GitHub Actions runners to Ubuntu 24.04

app/components/alert.hbs, app/components/alert.ts
Introduce an optional isInteractive argument to the alert component
that adds hover background color changes based on the alert color.
This improves user experience by providing visual feedback on
interactive alerts, enhancing clarity and engagement without affecting
non-interactive alerts.
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #3108 
- <kbd>&nbsp;1&nbsp;</kbd> #3109 👈
=> feat(alert): add interactive hover state styles for alerts

app/components/course-page/current-step-complete-modal.hbs, app/components/course-page/current-step-complete-modal.ts, app/components/course-page/current-step-complete-modal/language-leaderboard-rank-section.hbs, app/components/course-page/current-step-complete-modal/language-leaderboard-rank-section.ts, app/utils/repository-poller.ts, mirage/handlers/leaderboard-rank-calculations.js, tests/acceptance/course-page/attempt-course-stage-test.js, tests/acceptance/course-page/submit-course-stage-feedback-test.js, tests/acceptance/course-page/view-course-stages-test.js, tests/pages/course-page.ts
Display the user's leaderboard rank for the repository language when completing
a CourseStageStep. Hide the generic completion notice for stage steps and
replace it with a detailed LanguageLeaderboardRankSection.
Update the Mirage handler to use the current authenticated user and calculate
the correct leaderboard rank dynamically. Include the language leaderboard
relationship during repository polling to support these enhancements.
This provides users with immediate feedback on their ranking progress after
completing significant course stages, improving engagement and motivation.
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #3108 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #3109
=> feat(course-page): show language leaderboard rank on stage completion

config/environment.js
Update the major version number from 35.0 to 36.0 in the environment
configuration to force all clients to update. This ensures that users
are running the latest version after recent significant changes.
=> fix(config): bump app major version to 36.0

app/components/course-page/current-step-complete-modal/language-leaderboard-rank-section.hbs
Update language leaderboard rank section to support dark mode by
adding appropriate text and border color classes. This improves
visibility and consistency for users in dark theme settings.
=> fix(ui): add dark mode styles to leaderboard rank section

app/components/gift-payment-page/choose-plan-step-container.hbs, app/components/gift-payment-page/choose-plan-step-container.ts, app/components/gift-payment-page/confirm-and-pay-step-container.hbs, app/components/gift-payment-page/confirm-and-pay-step-container.ts, app/components/gift-payment-page/enter-details-step-container.hbs, app/components/gift-payment-page/enter-details-step-container.ts, app/components/gift-payment-page/gift-details-form/section.hbs, app/components/gift-payment-page/gift-details-form/section.ts, app/components/gift-payment-page/navigation-container-item.hbs, app/components/gift-payment-page/navigation-container-item.ts, app/components/gift-payment-page/navigation-container.hbs, app/components/gift-payment-page/navigation-container.ts, app/components/gift-payment-page/step-container.hbs, app/components/gift-payment-page/step-container.ts, app/components/pay-page/choose-membership-plan-modal.ts, app/components/pay-page/choose-membership-plan-modal/invoice-details-step.hbs, app/components/pay-page/choose-membership-plan-modal/plan-card.hbs, app/components/pay-page/choose-membership-plan-modal/plan-selection-step.hbs, app/controllers/gifts/buy.ts, app/models/gift-payment-flow.ts, app/router.ts, app/routes/gifts/buy.ts, app/templates/gifts/buy.hbs, mirage/config.js, mirage/handlers/gift-payment-flows.js, tests/acceptance/buy-gift-page/purchase-test.js, tests/pages/gift-payment-page.ts
Introduce a new gift payment flow feature under /gifts/buy route that
supports creating or fetching a gift payment session. Implement a
multi-step navigation component to guide users through the gift
purchase process, tracking completed and current steps within the
controller. Add data model for gift payment flow to store user inputs,
and create corresponding page objects for easier testing and interaction.
These changes enable anonymous access and enhance user experience by
providing clear navigation and state management throughout the payment
steps.
=> feat(gifts): add gift payment flow with multi-step navigation

.cursor/rules/development-workflow.mdc
Update the development workflow documentation to clarify the linting
and testing process. Advise running `npm run lint` after making
changes and only running tests selectively using `npx run ember test`
with module names, instead of using slow commands like `npm test` or
`npm run test`. Provide guidance on finding the module name in test
files or asking for help when unsure.
=> docs: improve development workflow linting and testing guidelines

app/components/course-page/setup-step/repository-setup-card/clone-repository-step.hbs
Replace conditional styled message with a clearer prompt to run commands
only when setup is incomplete. This improves user guidance by removing the
redundant "Listening for a git push" explanation and showing a concise
instruction until the step is marked complete.
=> feat(course-page): simplify instructions after cloning repository
