codecrafters-io/frontend

app/components/user-page/course-progress-list-item.js, app/models/course-participation.ts, tests/acceptance/view-user-profile-test.js
Reverts codecrafters-io/frontend#1467
=> Revert "refactor: Updated CourseParticipationModel to include completedStageSlugs."

package-lock.json
- Update @babel/helper-create-class-features-plugin to v7.24.4
- Update @babel/plugin-syntax-typescript to v7.24.1
- Update @babel/plugin-transform-typescript to v7.24.4
- Update @babel/runtime to v7.24.4
=> build: Update @babel packages to latest versions

app/models/submission.ts, tests/acceptance/course-page/attempt-course-stage-test.js, tests/acceptance/course-page/view-test-results-test.js
Add clientType attribute to Submission model with values 'cli' or 'git'.
Update related methods to check if submission was submitted via CLI or Git.
=> feat: Add clientType attribute to Submission model

app/components/course-page/course-stage-step/community-solution-card.ts, app/components/course-page/course-stage-step/community-solutions-list.hbs, app/components/course-page/course-stage-step/community-solutions-list.ts, app/mixins/viewable.js, app/models/view.ts
- Refactor mixins for upvoting and downvoting to a single mixin for voting.
- Refactor votable mixin: Remove unused imports and properties
- Refactor Votable mixin: move allUpvotes getter below allDownvotes getter
- Add onExpand event handler to CommunitySolutionCardComponent and CommunitySolutionsListComponent. When the onExpand event is triggered, it checks if the user is authenticated and then calls the createView method on the solution model, passing the position_in_list metadata. The createView method creates a new view record in the database with the resource ID, resource type, current user, and additional metadata. This allows tracking of views for each solution in the community solutions list.
=> Track position in list for view

app/controllers/track.js, tests/acceptance/track-page/view-track-test.js
=> CC-1285 Allow challenge deprecation in the tracks page

app/components/user-page/course-progress-list.ts, tests/acceptance/view-user-profile-test.js
=> CC-1285 Allow challenge deprecation in the user profile page

app/templates/course/stage/instructions.hbs
=> Tweak "Help us improve stage 2" CTA

app/components/helpscout-beacon.js
Refactor the HelpScoutBeaconComponent to prevent initialization 
during FastBoot. The changes ensure that the Beacon is only 
initialized in a browser environment, enhancing compatibility 
and preventing errors during server-side rendering. The code 
is streamlined for better readability and maintainability.
=> feat: improve HelpScout Beacon initialization logic

package-lock.json
Updates several dependencies in package-lock.json to their latest 
versions, including @keyv/serialize, semver, ember-template-imports, 
and ws. These changes improve security, compatibility, and performance 
by incorporating the latest bug fixes and features from the respective 
packages.
=> fix(deps): update dependencies to latest versions

app/index.html, tests/index.html
Integrate HelpScout Beacon and Facebook Pixel tracking scripts 
into the index.html files for both tests and app. This enhances 
the ability to monitor user interactions and behavior, which 
is critical for improving customer
=> feat(tracking): add HelpScout Beacon and Facebook Pixel scripts

vercel.json
Adds a redirect to the maintenance page for all routes. This change 
ensures users are directed to a relevant page during site maintenance, 
improving user experience and communication.
=> feat: add maintenance redirect to vercel.json

vercel.json
Eliminate the temporary redirect to the maintenance page in 
vercel.json, streamlining the routing for users. This change 
prevents unnecessary detours for visitors and enhances overall 
user experience during deployment.
=> refactor: remove maintenance redirect from vercel.json

app/components/course-admin/code-example-insights/metadata-container.ts, app/models/community-course-stage-solution.ts
Adds a new `flakinessCheckStatus` attribute to the 
`CommunityCourseStageSolution` model, representing different 
states of the flakiness check. Implements a computed property 
to format flakiness check status messages in the metadata 
container, enhancing user feedback and visibility on the 
flakiness checks associated with course solutions.
=> feat: add flakiness check status to course stage solution

config/environment.js
Increments the major version number in the environment configuration  
to 33.0 to ensure all clients receive the latest updates, preparing  
for future enhancements.
=> feat: update version number to 33.0 in environment config

app/components/course-page/base-stages-completed-card.hbs, app/components/course-page/base-stages-completed-card.ts
=> CC-1782: Tweak copy in "base stages completed" section

app/components/header/index.ts
=> Add Roadmap to Navbar for Anon Users

app/components/roadmap-page/course-extension-idea-card.hbs, app/components/roadmap-page/course-idea-card.gts, app/components/roadmap-page/idea-card/vote-button.gts, app/templates/roadmap/course-extension-ideas.hbs, app/templates/roadmap/course-ideas.hbs, tests/acceptance/roadmap-page/course-extension-ideas-test.js, tests/acceptance/roadmap-page/course-ideas-test.js, tests/pages/roadmap-page.js
=> Redrawing the roadmap (vote) pages

app/components/course-page/course-stage-step/community-solution-card/header-label.hbs
=> Change community solution of the concise solution warning

app/controllers/roadmap/course-extension-ideas.ts, mirage/data/course-extension-ideas.js
=> Hide extension ideas if all extension ideas as released

app/components/course-dropdown.hbs
=> Fix dropdown colors

app/components/institution-page/claim-offer-button.hbs, app/components/institution-page/claim-offer-button.ts, app/components/institution-page/claim-offer-card.hbs, app/components/institution-page/claim-offer-card.ts, app/controllers/institution.ts, app/models/institution.ts, app/router.ts, app/routes/institution.ts, app/templates/institution.hbs
=> Add institution page

app/components/institution-page/campus-program-application-modal/enter-email-step.ts, app/models/institution-membership-grant-application.ts
=> Store both originalEmailAddress and normalizedEmailAddress

app/components/institution-page/campus-program-application-modal.hbs, app/components/institution-page/campus-program-application-modal.ts, app/components/institution-page/campus-program-application-modal/enter-email-step-container.hbs, app/components/institution-page/campus-program-application-modal/enter-email-step-container.ts, app/components/institution-page/campus-program-application-modal/verify-email-step-container.hbs, app/components/institution-page/campus-program-application-modal/verify-email-step-container.ts, app/models/institution-membership-grant-application.ts, app/models/user.ts, mirage/handlers/institution-membership-grant-applications.js, tests/acceptance/institution-page/claim-offer-test.js, tests/pages/institution-page.ts
=> feat: implement email verification step in application modal

app/models/subscription.ts
=> refactor: remove unused subscription model actions and methods

app/mixins/viewable.js, app/models/view.ts
=> refactor: simplify view creation by using resource relation

app/models/subscription.ts, tests/acceptance/settings-page/billing-test.js, tests/support/authentication-helpers.js
=> refactor: remove pricingPlanName from subscription model

app/components/affiliate-page/affiliate-referred-user-item.hbs, app/models/affiliate-referral.ts, tests/acceptance/affiliate-page/view-affiliate-referrals-test.js
=> refactor: remove upcoming payment logic from affiliate referral

app/components/settings/billing-page/payment-history-section.hbs
=> style: adjust font size for 'No payments found' text

app/components/course-page/configure-extensions-modal/index.ts
=> Use the correct function for sortPos

app/components/institution-page/campus-program-application-modal.hbs, app/components/institution-page/campus-program-application-modal.ts, app/models/email-address.ts, app/models/user.ts, app/routes/institution.ts, mirage/config.js, mirage/handlers/email-addresses.js, tests/acceptance/institution-page/claim-offer-test.js
=> Pre fill email addresses from GitHub profile

app/components/course-page/introduction-step/create-repository-card/requested-languages-prompt.hbs, app/components/course-page/introduction-step/create-repository-card/requested-languages-prompt.ts, app/components/course-page/introduction-step/create-repository-card/select-language-section.hbs
Fixes https://github.com/codecrafters-io/frontend/issues/3067
=> Update contribution link to course repo

app/components/leaderboard-page/entries-table.hbs, app/components/leaderboard-page/entries-table.ts, app/components/leaderboard-page/entries-table/filler-row.hbs, app/components/leaderboard-page/entries-table/filler-row.ts, app/components/leaderboard-page/entries-table/header-row-cell.hbs, app/components/leaderboard-page/entries-table/header-row-cell.ts, app/components/leaderboard-page/entries-table/row-cell.hbs, app/components/leaderboard-page/entries-table/row-cell.ts, app/components/leaderboard-page/entries-table/row.hbs, app/components/leaderboard-page/entries-table/row.ts, app/components/leaderboard-page/header.hbs, app/components/leaderboard-page/header.ts, app/controllers/leaderboard.ts, app/models/language.ts, app/models/leaderboard-entry.ts, app/router.ts, app/routes/leaderboard.ts, app/styles/utilities.css, app/templates/leaderboard.hbs, mirage/handlers/leaderboard-entries.js, tests/acceptance/leaderboard-page/view-test.js, tests/pages/leaderboard-page.ts
feat(leaderboard): enhance layout and responsiveness of header and entries table
refactor: remove unused leaderboard handler and update models
=> feat: add leaderboard feature with language dropdown and entries table

.vscode/settings.json, app/components/track-page/course-card-list.ts, tests/acceptance/track-page/view-track-test.js
=> Sort courses by progress and submission time in TrackPageCourseCardList.

app/controllers/track.ts
=> Filter out deprecated courses for staff users in TrackController.
